/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as OwnerUnitsRouteImport } from './routes/owner.units'
import { Route as OwnerRequestsRouteImport } from './routes/owner.requests'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as OwnerMetersRouteImport } from './routes/owner.meters'
import { Route as OwnerBuildingsRouteImport } from './routes/owner.buildings'
import { Route as OwnerAmenitiesRouteImport } from './routes/owner.amenities'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerUnitsRoute = OwnerUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRequestsRoute = OwnerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMetersRoute = OwnerMetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBuildingsRoute = OwnerBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAmenitiesRoute = OwnerAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/amenities': typeof OwnerAmenitiesRoute
  '/owner/buildings': typeof OwnerBuildingsRoute
  '/owner/meters': typeof OwnerMetersRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/amenities': typeof OwnerAmenitiesRoute
  '/owner/buildings': typeof OwnerBuildingsRoute
  '/owner/meters': typeof OwnerMetersRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/amenities': typeof OwnerAmenitiesRoute
  '/owner/buildings': typeof OwnerBuildingsRoute
  '/owner/meters': typeof OwnerMetersRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/owner'
    | '/register'
    | '/admin/users'
    | '/owner/amenities'
    | '/owner/buildings'
    | '/owner/meters'
    | '/owner/properties'
    | '/owner/requests'
    | '/owner/units'
    | '/properties/$propertyId'
    | '/admin/'
    | '/owner/'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/owner/amenities'
    | '/owner/buildings'
    | '/owner/meters'
    | '/owner/properties'
    | '/owner/requests'
    | '/owner/units'
    | '/properties/$propertyId'
    | '/admin'
    | '/owner'
    | '/properties'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/owner'
    | '/register'
    | '/admin/users'
    | '/owner/amenities'
    | '/owner/buildings'
    | '/owner/meters'
    | '/owner/properties'
    | '/owner/requests'
    | '/owner/units'
    | '/properties/$propertyId'
    | '/admin/'
    | '/owner/'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/units': {
      id: '/owner/units'
      path: '/units'
      fullPath: '/owner/units'
      preLoaderRoute: typeof OwnerUnitsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/requests': {
      id: '/owner/requests'
      path: '/requests'
      fullPath: '/owner/requests'
      preLoaderRoute: typeof OwnerRequestsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/meters': {
      id: '/owner/meters'
      path: '/meters'
      fullPath: '/owner/meters'
      preLoaderRoute: typeof OwnerMetersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/buildings': {
      id: '/owner/buildings'
      path: '/buildings'
      fullPath: '/owner/buildings'
      preLoaderRoute: typeof OwnerBuildingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/amenities': {
      id: '/owner/amenities'
      path: '/amenities'
      fullPath: '/owner/amenities'
      preLoaderRoute: typeof OwnerAmenitiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerRouteChildren {
  OwnerAmenitiesRoute: typeof OwnerAmenitiesRoute
  OwnerBuildingsRoute: typeof OwnerBuildingsRoute
  OwnerMetersRoute: typeof OwnerMetersRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRoute
  OwnerRequestsRoute: typeof OwnerRequestsRoute
  OwnerUnitsRoute: typeof OwnerUnitsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAmenitiesRoute: OwnerAmenitiesRoute,
  OwnerBuildingsRoute: OwnerBuildingsRoute,
  OwnerMetersRoute: OwnerMetersRoute,
  OwnerPropertiesRoute: OwnerPropertiesRoute,
  OwnerRequestsRoute: OwnerRequestsRoute,
  OwnerUnitsRoute: OwnerUnitsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
