/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TenantRentalsRouteImport } from './routes/tenant.rentals'
import { Route as TenantPaymentsRouteImport } from './routes/tenant.payments'
import { Route as TenantContractsRouteImport } from './routes/tenant.contracts'
import { Route as TenantAmenitiesRouteImport } from './routes/tenant.amenities'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as OwnerUnitsRouteImport } from './routes/owner.units'
import { Route as OwnerRequestsRouteImport } from './routes/owner.requests'
import { Route as OwnerPropertiesRouteImport } from './routes/owner.properties'
import { Route as OwnerMetersRouteImport } from './routes/owner.meters'
import { Route as OwnerBuildingsRouteImport } from './routes/owner.buildings'
import { Route as OwnerAmenitiesRouteImport } from './routes/owner.amenities'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TenantRentalsRoute = TenantRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPaymentsRoute = TenantPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => TenantRoute,
} as any)
const TenantContractsRoute = TenantContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => TenantRoute,
} as any)
const TenantAmenitiesRoute = TenantAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => TenantRoute,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerUnitsRoute = OwnerUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerRequestsRoute = OwnerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMetersRoute = OwnerMetersRouteImport.update({
  id: '/meters',
  path: '/meters',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerBuildingsRoute = OwnerBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAmenitiesRoute = OwnerAmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/tenant': typeof TenantRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/owner/amenities': typeof OwnerAmenitiesRoute
  '/owner/buildings': typeof OwnerBuildingsRoute
  '/owner/meters': typeof OwnerMetersRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/tenant/amenities': typeof TenantAmenitiesRoute
  '/tenant/contracts': typeof TenantContractsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/owner/amenities': typeof OwnerAmenitiesRoute
  '/owner/buildings': typeof OwnerBuildingsRoute
  '/owner/meters': typeof OwnerMetersRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/tenant/amenities': typeof TenantAmenitiesRoute
  '/tenant/contracts': typeof TenantContractsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/admin': typeof AdminIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/register': typeof RegisterRoute
  '/tenant': typeof TenantRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/owner/amenities': typeof OwnerAmenitiesRoute
  '/owner/buildings': typeof OwnerBuildingsRoute
  '/owner/meters': typeof OwnerMetersRoute
  '/owner/properties': typeof OwnerPropertiesRoute
  '/owner/requests': typeof OwnerRequestsRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/tenant/amenities': typeof TenantAmenitiesRoute
  '/tenant/contracts': typeof TenantContractsRoute
  '/tenant/payments': typeof TenantPaymentsRoute
  '/tenant/rentals': typeof TenantRentalsRoute
  '/admin/': typeof AdminIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/owner'
    | '/register'
    | '/tenant'
    | '/admin/users'
    | '/owner/amenities'
    | '/owner/buildings'
    | '/owner/meters'
    | '/owner/properties'
    | '/owner/requests'
    | '/owner/units'
    | '/properties/$propertyId'
    | '/tenant/amenities'
    | '/tenant/contracts'
    | '/tenant/payments'
    | '/tenant/rentals'
    | '/admin/'
    | '/owner/'
    | '/properties/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/owner/amenities'
    | '/owner/buildings'
    | '/owner/meters'
    | '/owner/properties'
    | '/owner/requests'
    | '/owner/units'
    | '/properties/$propertyId'
    | '/tenant/amenities'
    | '/tenant/contracts'
    | '/tenant/payments'
    | '/tenant/rentals'
    | '/admin'
    | '/owner'
    | '/properties'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/owner'
    | '/register'
    | '/tenant'
    | '/admin/users'
    | '/owner/amenities'
    | '/owner/buildings'
    | '/owner/meters'
    | '/owner/properties'
    | '/owner/requests'
    | '/owner/units'
    | '/properties/$propertyId'
    | '/tenant/amenities'
    | '/tenant/contracts'
    | '/tenant/payments'
    | '/tenant/rentals'
    | '/admin/'
    | '/owner/'
    | '/properties/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  TenantRoute: typeof TenantRouteWithChildren
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tenant/rentals': {
      id: '/tenant/rentals'
      path: '/rentals'
      fullPath: '/tenant/rentals'
      preLoaderRoute: typeof TenantRentalsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/payments': {
      id: '/tenant/payments'
      path: '/payments'
      fullPath: '/tenant/payments'
      preLoaderRoute: typeof TenantPaymentsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/contracts': {
      id: '/tenant/contracts'
      path: '/contracts'
      fullPath: '/tenant/contracts'
      preLoaderRoute: typeof TenantContractsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/amenities': {
      id: '/tenant/amenities'
      path: '/amenities'
      fullPath: '/tenant/amenities'
      preLoaderRoute: typeof TenantAmenitiesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/units': {
      id: '/owner/units'
      path: '/units'
      fullPath: '/owner/units'
      preLoaderRoute: typeof OwnerUnitsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/requests': {
      id: '/owner/requests'
      path: '/requests'
      fullPath: '/owner/requests'
      preLoaderRoute: typeof OwnerRequestsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/meters': {
      id: '/owner/meters'
      path: '/meters'
      fullPath: '/owner/meters'
      preLoaderRoute: typeof OwnerMetersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/buildings': {
      id: '/owner/buildings'
      path: '/buildings'
      fullPath: '/owner/buildings'
      preLoaderRoute: typeof OwnerBuildingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/amenities': {
      id: '/owner/amenities'
      path: '/amenities'
      fullPath: '/owner/amenities'
      preLoaderRoute: typeof OwnerAmenitiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OwnerRouteChildren {
  OwnerAmenitiesRoute: typeof OwnerAmenitiesRoute
  OwnerBuildingsRoute: typeof OwnerBuildingsRoute
  OwnerMetersRoute: typeof OwnerMetersRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRoute
  OwnerRequestsRoute: typeof OwnerRequestsRoute
  OwnerUnitsRoute: typeof OwnerUnitsRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAmenitiesRoute: OwnerAmenitiesRoute,
  OwnerBuildingsRoute: OwnerBuildingsRoute,
  OwnerMetersRoute: OwnerMetersRoute,
  OwnerPropertiesRoute: OwnerPropertiesRoute,
  OwnerRequestsRoute: OwnerRequestsRoute,
  OwnerUnitsRoute: OwnerUnitsRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface TenantRouteChildren {
  TenantAmenitiesRoute: typeof TenantAmenitiesRoute
  TenantContractsRoute: typeof TenantContractsRoute
  TenantPaymentsRoute: typeof TenantPaymentsRoute
  TenantRentalsRoute: typeof TenantRentalsRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantAmenitiesRoute: TenantAmenitiesRoute,
  TenantContractsRoute: TenantContractsRoute,
  TenantPaymentsRoute: TenantPaymentsRoute,
  TenantRentalsRoute: TenantRentalsRoute,
  TenantIndexRoute: TenantIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  RegisterRoute: RegisterRoute,
  TenantRoute: TenantRouteWithChildren,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
